services:
  accountservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=6001
      #- ASPNETCORE_HTTPS_PORTS=7001
    ports:
      - "6001:6001"
      #- "7001"
    depends_on:
      - rabbitmq
      - accountdb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  transferservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=6002
      #- ASPNETCORE_HTTPS_PORTS=7002
    ports:
      - "6002:6002"
      #- "7002"
    depends_on:
      - rabbitmq
      - transferdb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  accountdb:
    container_name: accountdb
    environment:
      SA_PASSWORD: "Admin1234"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1430:1433"
    volumes:
      - account_sql_data:/var/opt/mssql

  transferdb:
    container_name: transferdb
    environment:
      SA_PASSWORD: "Admin1234"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1431:1433"
    volumes:
      - transfer_sql_data:/var/opt/mssql

  rabbitmq:
    container_name: rabbitmq
    restart: always
    environment:
    - RabbitMQ_USER=guest
    - RabbitMQ_PASSWORD=guest
    ports:
    - "5672:5672"
    - "15672:15672"
