version: '3.4'

services:
  accountservice.api:
    image: ${DOCKER_REGISTRY-}accountserviceapi
    build:
      context: ./AccountService/AccountService.API
      dockerfile: AccountService.API/Dockerfile
