services:
  accountservice.api:
    image: ${DOCKER_REGISTRY-}accountserviceapi
    build:
      context: ./AccountService
      dockerfile: ./AccountService.API/Dockerfile

  transferservice.api:
    image: ${DOCKER_REGISTRY-}transferserviceapi
    build:
      context: ./TransferService
      dockerfile: ./TransferService.API/Dockerfile
